### ISSUE TITLE
Seeing post from friends of friends

### ISSUE THREAD

**Issue by Ihavetofind** [yandevelop/Bea#20]
Hi, I have Bea 1.12 installed but i cannot seem to be able to see friends of friends’ posts when I haven’t posted. I can see them when I post as well but it doesn’t work when I have t posted, although I can see my direct friends’ post even when I have t posted.

Is this a problem on my end or is that how the app works? If so I hope you can solve it in the next releases as otherwise I absolutely enjoy the app and would like to use this opportunity to thank you.

**Comment by yandevelop** [comment]
Thanks for your kind words! This is how the app works. You can see your "direct friends" BeReals because my tweak unblurs them. I started working on also "unblurring" the friends of friends feed but it's different to how normal BeReals are getting unblurred. 
BeReal updated their API while I worked on a feature for unblurring Friends of friends and now my method of showing those BeReals doesn't work anymore.

**Comment by Ihavetofind** [comment]
Ok than, thanks for your work. I hope you can crack this new/different API at a point as well.
